name: delizia
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

# consider running `flutter pub upgrade --major-versions`. Alternatively,
dependencies:
  bloc: ^9.0.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_map: ^7.0.2
  flutter_map_location_marker: ^9.1.1
  flutter_polyline_points: ^2.1.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  formz: ^0.8.0
  get_it: ^8.0.3
  go_router: ^14.7.2
  http: ^1.3.0
  latlong2: ^0.9.1
  location: ^7.0.1
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/img/
    - assets/banner/
    - assets/icons/
    - assets/agencies/
    - assets/json/
    - assets/products/
